agent:
  name: claude-3-haiku-20240307
  system_promt: "You are a financial analysis agent with access to tools that can retrieve up-to-date stock data. Your task is to analyze the current market data and help perform trading tasks."

dev: testing
